apiVersion: apps/v1
kind: Deployment
metadata:
  name: kards
  namespace: mdev
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: kards
          image: 'gcr.io/my-kubernates-project-338709/kards123:latest'
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '500Mi'
              cpu: '200m'
            limits:
              memory: '1000Mi'
              cpu: '500m'
          # livenessProbe:
          #   failureThreshold: 3
          #   initialDelaySeconds: 60
          #   periodSeconds: ''
          #   timeoutSeconds: 1
          #   exec:
          #     command:
          #       - >-
          #         /bin/sh -c "touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy;
          #         sleep 600"

---

apiVersion: v1
kind: Service
metadata:
  name: kards
  namespace: mdev
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
